example:
  property: "GATEWAY"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapplication?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bootcamp
    password: ENC(P7rd1qtmgE9J6Gbip8J2Hsa3nwmzmGnX)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8090

